### ISSUE TITLE
Incorrect Cpp code for bindings without arguments

### ISSUE THREAD

**Issue by adambabik** [status-im/status-nodejs#1]
Take a look at `StopNode` binding which has a signature `func StopNode() *C.char`. 

This is a corresponding generated C++ function:
```cpp
void _StopNode(const FunctionCallbackInfo<Value>& args) {
	Isolate* isolate = args.GetIsolate();

	if (args.Length() != 0) {
		// Throw an Error that is passed back to JavaScript
		isolate->ThrowException(Exception::TypeError(
			String::NewFromUtf8(isolate, "Wrong number of arguments for StopNode")));
		return;
	}

	// Check the argument types
	

	

	// Call exported Go function, which returns a C string
	char *c = StopNode();

	Local<String> ret = String::NewFromUtf8(isolate, c);
	args.GetReturnValue().Set(ret);
	delete c;
}
```

Especially, notice `if (args.Length() != 0)` which is incorrect.

**Comment by divan** [comment]
@adambabik what should `args.Length()` return in case of "no arguments"?

**Comment by adambabik** [comment]
@divan I believe `args.Length() == 0` so the condition should be different. Now, it requires non-zero number of arguments while a binding requires exactly no arguments.

**Comment by divan** [comment]
@adambabik either you or I need more coffee :) From my understanding, this condition, if true (non-zero number of arguments) triggers an error. For zero number of arguments, it will proceed as planned, no?

**Comment by adambabik** [comment]
@divan oh man, so sorry. It's definitely me... All is ok, it was a totally different problem in JS code. Closing.
